{
 "title": "EdgeRouter",
 "tags": [ "snmp" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "wan",
    "label": "Internet interface",
    "query": {
     "query": "label_values(ifHCInOctets{job=\"edgerouter\"}, ifName)"
    }
   },
   {
    "name": "interface",
    "label": "Interfaces",
    "query": {
     "query": "label_values(ifHCInOctets{job=\"edgerouter\", ifName!~\"lo|imq.*\"}, ifName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrSystemUptime{job=\"edgerouter\"} / 100",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "CPU busy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - rate(ssCpuRawIdle{job=\"edgerouter\"}[$__rate_interval]) / ssCpuNumCpus{job=\"edgerouter\"}",
     "legendFormat": "CPU busy"
    }
   ]
  },
  {
   "title": "Memory used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(memTotalReal{job=\"edgerouter\"} - memAvailReal{job=\"edgerouter\"} - memBuffer{job=\"edgerouter\"} - memCached{job=\"edgerouter\"}) / memTotalReal{job=\"edgerouter\"} * 100",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "Load (1 min)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laLoadFloat{job=\"edgerouter\", laNames=\"Load-1\"}",
     "legendFormat": "Load (1 min)"
    }
   ]
  },
  {
   "title": "Internet down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{job=\"edgerouter\", ifName=\"$wan\"}[$__rate_interval]) * 8",
     "legendFormat": "Internet down"
    }
   ]
  },
  {
   "title": "Internet up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{job=\"edgerouter\", ifName=\"$wan\"}[$__rate_interval]) * 8",
     "legendFormat": "Internet up"
    }
   ]
  },
  {
   "title": "Internet traffic ($wan)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{job=\"edgerouter\", ifName=\"$wan\"}[$__rate_interval]) * 8",
     "legendFormat": "Download"
    },
    {
     "expr": "rate(ifHCOutOctets{job=\"edgerouter\", ifName=\"$wan\"}[$__rate_interval]) * 8",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Receive by interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{job=\"edgerouter\", ifName=~\"$interface\"}[$__rate_interval]) * 8",
     "legendFormat": "{{ifName}} {{ifAlias}}"
    }
   ]
  },
  {
   "title": "Transmit by interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{job=\"edgerouter\", ifName=~\"$interface\"}[$__rate_interval]) * 8",
     "legendFormat": "{{ifName}} {{ifAlias}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(ssCpuRawUser{job=\"edgerouter\"}[$__rate_interval]) / ssCpuNumCpus{job=\"edgerouter\"}",
     "legendFormat": "User"
    },
    {
     "expr": "rate(ssCpuRawNice{job=\"edgerouter\"}[$__rate_interval]) / ssCpuNumCpus{job=\"edgerouter\"}",
     "legendFormat": "Nice"
    },
    {
     "expr": "rate(ssCpuRawSystem{job=\"edgerouter\"}[$__rate_interval]) / ssCpuNumCpus{job=\"edgerouter\"}",
     "legendFormat": "System"
    },
    {
     "expr": "rate(ssCpuRawSoftIRQ{job=\"edgerouter\"}[$__rate_interval]) / ssCpuNumCpus{job=\"edgerouter\"}",
     "legendFormat": "SoftIRQ"
    },
    {
     "expr": "rate(ssCpuRawInterrupt{job=\"edgerouter\"}[$__rate_interval]) / ssCpuNumCpus{job=\"edgerouter\"}",
     "legendFormat": "Interrupt"
    },
    {
     "expr": "rate(ssCpuRawWait{job=\"edgerouter\"}[$__rate_interval]) / ssCpuNumCpus{job=\"edgerouter\"}",
     "legendFormat": "Wait"
    },
    {
     "expr": "rate(ssCpuRawSteal{job=\"edgerouter\"}[$__rate_interval]) / ssCpuNumCpus{job=\"edgerouter\"}",
     "legendFormat": "Steal"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(memTotalReal{job=\"edgerouter\"} - memAvailReal{job=\"edgerouter\"} - memBuffer{job=\"edgerouter\"} - memCached{job=\"edgerouter\"}) * 1024",
     "legendFormat": "Used"
    },
    {
     "expr": "memBuffer{job=\"edgerouter\"} * 1024",
     "legendFormat": "Buffers"
    },
    {
     "expr": "memCached{job=\"edgerouter\"} * 1024",
     "legendFormat": "Cached"
    },
    {
     "expr": "memAvailReal{job=\"edgerouter\"} * 1024",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Load average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "laLoadFloat{job=\"edgerouter\"}",
     "legendFormat": "{{laNames}}"
    }
   ]
  },
  {
   "title": "Errors and discards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInErrors{job=\"edgerouter\", ifName=~\"$interface\"}[$__rate_interval]) > 0",
     "legendFormat": "{{ifName}} in errors"
    },
    {
     "expr": "rate(ifOutErrors{job=\"edgerouter\", ifName=~\"$interface\"}[$__rate_interval]) > 0",
     "legendFormat": "{{ifName}} out errors"
    },
    {
     "expr": "rate(ifInDiscards{job=\"edgerouter\", ifName=~\"$interface\"}[$__rate_interval]) > 0",
     "legendFormat": "{{ifName}} in discards"
    },
    {
     "expr": "rate(ifOutDiscards{job=\"edgerouter\", ifName=~\"$interface\"}[$__rate_interval]) > 0",
     "legendFormat": "{{ifName}} out discards"
    }
   ]
  }
 ]
}